# Generated by Django 3.0.2 on 2020-01-11 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50, verbose_name='Enter Filename')),
                ('database', models.FileField(upload_to=None, verbose_name='Database')),
                ('db_for', models.CharField(max_length=50, verbose_name='Database of')),
                ('database_size', models.IntegerField(verbose_name='Database Size')),
            ],
            options={
                'verbose_name': 'CandidateDatabase',
                'verbose_name_plural': 'CandidateDatabases',
            },
        ),
        migrations.CreateModel(
            name='TaskDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('activity', models.CharField(max_length=50, verbose_name='Activity Done')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Activity Quantity')),
                ('content', models.TextField(verbose_name='Content')),
                ('output', models.CharField(max_length=50, verbose_name='Output')),
            ],
            options={
                'verbose_name': 'TaskDone',
                'verbose_name_plural': 'TaskDones',
            },
        ),
    ]
