# Generated by Django 3.0.2 on 2020-01-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdone',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='database_records.CandidateDatabase', verbose_name='Database'),
        ),
    ]
