# Generated by Django 3.0.2 on 2020-01-16 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database_records', '0002_taskdone_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdone',
            name='activity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Activity Done'),
        ),
        migrations.AlterField(
            model_name='taskdone',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='taskdone',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='taskdone',
            name='output',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Output'),
        ),
    ]
