# Generated by Django 3.0.2 on 2020-01-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_records', '0003_auto_20200116_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdone',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
    ]
