# Generated by Django 3.0.2 on 2020-01-16 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database_records', '0004_auto_20200116_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskdone',
            options={'verbose_name': 'TaskDone', 'verbose_name_plural': 'TasksDone'},
        ),
        migrations.AddField(
            model_name='candidatedatabase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
    ]
