# Generated by Django 3.0.2 on 2020-01-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_records', '0005_auto_20200116_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdone',
            name='activity_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Activity Range'),
        ),
    ]
